[package]
name = "playground"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio", "tls-native-tls"] }
tokio = { version = "1", features = ["full"] }
fake = { version = "4", features = ["derive"] }
